# Generated by Django 4.1.2 on 2022-10-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("valor", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "administrador_configuracao",
            },
        ),
    ]
