# Generated by Django 4.1.2 on 2022-10-23 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantidade", models.IntegerField()),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("imagem_principal", models.ImageField(upload_to="produto")),
                ("descricao", models.TextField(null=True)),
                ("status", models.BooleanField()),
                ("data_cad", models.DateField()),
                ("dat_edit", models.DateField(null=True)),
            ],
            options={
                "db_table": "administrador_produto",
            },
        ),
        migrations.CreateModel(
            name="ProdutoAtributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("valor", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "administrador_produto_atributo",
            },
        ),
        migrations.CreateModel(
            name="ProdutoCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("icone", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "administrador_produto_categoria",
            },
        ),
        migrations.CreateModel(
            name="ProdutoTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_id",
                    models.IntegerField(
                        choices=[(1, "Ofertas"), (2, "Novidades"), (3, "Todos")]
                    ),
                ),
            ],
            options={
                "db_table": "administrador_produto_tipo",
            },
        ),
        migrations.CreateModel(
            name="ProdutoImagens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="produto/imagens")),
                ("data_cad", models.DateField()),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produto",
                    ),
                ),
                (
                    "user_cad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "administrador_produto_imagens",
            },
        ),
        migrations.CreateModel(
            name="ProdutoAtributoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atributo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produtoatributo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produto",
                    ),
                ),
            ],
            options={
                "db_table": "administrador_produto_atributo_produto",
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produto.produtocategoria",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="produto.produtotipo",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="user_cad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
