# Generated by Django 4.1.2 on 2022-11-11 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiamentrosProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nCdServico",
                    models.CharField(
                        choices=[
                            ("04014", "SEDEX à vista"),
                            ("04065", "SEDEX à vista pagamento na entrega"),
                            ("04510", "PAC à vista"),
                            ("04707", "PAC à vista pagamento na entrega"),
                            ("40169", "SEDEX 12 ( à vista e a faturar)"),
                            ("40215", "SEDEX 10 (à vista e a faturar)"),
                            ("40290", "SEDEX Hoje Varejo"),
                        ],
                        max_length=200,
                    ),
                ),
                ("sCepOrigem", models.CharField(max_length=200)),
                ("sCepDestino", models.CharField(max_length=200)),
                ("nVlPeso", models.CharField(max_length=200)),
                (
                    "nCdFormato",
                    models.IntegerField(
                        choices=[
                            (1, "Formato caixa/pacote"),
                            (2, "Formato rolo/prisma"),
                            (3, "Envelope"),
                        ]
                    ),
                ),
                (
                    "nVlComprimento",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "nVlAltura",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "nVlLargura",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "nVlDiametro",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produto",
                    ),
                ),
            ],
            options={
                "db_table": "administrador_produto_diametro",
            },
        ),
    ]
