# Generated by Django 4.1.2 on 2022-11-11 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0002_diamentrosproduto"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DiamentrosProduto",
            new_name="ProdutoDiamentro",
        ),
    ]
