# Generated by Django 4.1.2 on 2022-11-14 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0003_rename_diamentrosproduto_produtodiamentro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produtodiamentro",
            name="produto",
        ),
        migrations.AlterField(
            model_name="produtodiamentro",
            name="sCepDestino",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="ProdutoDiamentroProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diametro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produtodiamentro",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produto",
                    ),
                ),
            ],
            options={
                "db_table": "administrador_produto_diametro_produto",
            },
        ),
    ]
