# Generated by Django 4.1.2 on 2022-10-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("user", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("telefone", models.CharField(max_length=200)),
                ("cpf_cnpj", models.CharField(max_length=200)),
                ("data_nascimento", models.DateField()),
                ("senha", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "loja_cliente",
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=200)),
                ("estado", models.CharField(max_length=200)),
                ("cidade", models.CharField(max_length=200)),
                ("bairro", models.CharField(max_length=200, null=True)),
                ("logradouro", models.CharField(max_length=200, null=True)),
                ("nr_casa", models.IntegerField(null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "loja_cliente_endereco",
            },
        ),
    ]
