# Generated by Django 4.1.2 on 2022-11-07 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="user",
        ),
    ]
