# Generated by Django 4.1.2 on 2022-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cliente", "0004_cliente_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatar"),
        ),
    ]
